version: '3.8'

services:
  pre-prod54:
    image: krdh-services-i:v1
    container_name: pre-prod54
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Kolkata
      - JAVA_OPTS=-Duser.timezone=Asia/Kolkata
    volumes:
      - "/home/docker_krdh_services/webapps/:/usr/appserver/tomcat/webapps/"
      - "/home/docker_krdh_services/context.xml:/usr/appserver/tomcat/conf/context.xml"
      - "/home/docker_krdh_services/catalina.sh:/usr/appserver/tomcat/bin/catalina.sh"
      - "/opt/appdata/:/opt/appdata/"
      - "/usr/safenet/:/usr/safenet/"
      - "/etc/Chrystoki.conf:/etc/Chrystoki.conf"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
      - "/usr/share/zoneinfo/:/usr/share/zoneinfo"
      - "/etc/hosts:/etc/hosts"
    cap_add:
      - SYS_TIME
    restart: always
    deploy:
      replicas: 2  # Set the number of replicas here
--------------------------------------------------------------------------------------------------------------------------------------------------------------
docker swarm init
docker stack deploy -c docker-compose-swarm.yml krdhservices
